title: "Scala Pickling | Fast, Customizable, Static Serializers for Scala"

baseurl: ""
githuburl: "http://github.com/scala/pickling"
projecttitle: "Scala Pickling"
projecttagline: "Fast, Customizable, Static Serializers for Scala"
