title: "Scala Pickling | Fast, Customizable, Static Serializers for Scala"

githuburl: "http://github.com/heathermiller/scala-pickling"
projecttitle: "Scala Pickling"
projecttagline: "Fast, Customizable, Static Serializers for Scala"

